/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.twitter.flockdb.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EdgeResults implements org.apache.thrift.TBase<EdgeResults, EdgeResults._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EdgeResults");

  private static final org.apache.thrift.protocol.TField EDGES_FIELD_DESC = new org.apache.thrift.protocol.TField("edges", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField NEXT_CURSOR_FIELD_DESC = new org.apache.thrift.protocol.TField("next_cursor", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField PREV_CURSOR_FIELD_DESC = new org.apache.thrift.protocol.TField("prev_cursor", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new EdgeResultsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new EdgeResultsTupleSchemeFactory());
  }

  public List<Edge> edges; // required
  public long next_cursor; // required
  public long prev_cursor; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EDGES((short)1, "edges"),
    NEXT_CURSOR((short)2, "next_cursor"),
    PREV_CURSOR((short)3, "prev_cursor");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EDGES
          return EDGES;
        case 2: // NEXT_CURSOR
          return NEXT_CURSOR;
        case 3: // PREV_CURSOR
          return PREV_CURSOR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NEXT_CURSOR_ISSET_ID = 0;
  private static final int __PREV_CURSOR_ISSET_ID = 1;
  private BitSet __isset_bit_vector = new BitSet(2);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EDGES, new org.apache.thrift.meta_data.FieldMetaData("edges", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Edge.class))));
    tmpMap.put(_Fields.NEXT_CURSOR, new org.apache.thrift.meta_data.FieldMetaData("next_cursor", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PREV_CURSOR, new org.apache.thrift.meta_data.FieldMetaData("prev_cursor", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EdgeResults.class, metaDataMap);
  }

  public EdgeResults() {
  }

  public EdgeResults(
    List<Edge> edges,
    long next_cursor,
    long prev_cursor)
  {
    this();
    this.edges = edges;
    this.next_cursor = next_cursor;
    setNext_cursorIsSet(true);
    this.prev_cursor = prev_cursor;
    setPrev_cursorIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EdgeResults(EdgeResults other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetEdges()) {
      List<Edge> __this__edges = new ArrayList<Edge>();
      for (Edge other_element : other.edges) {
        __this__edges.add(new Edge(other_element));
      }
      this.edges = __this__edges;
    }
    this.next_cursor = other.next_cursor;
    this.prev_cursor = other.prev_cursor;
  }

  public EdgeResults deepCopy() {
    return new EdgeResults(this);
  }

  @Override
  public void clear() {
    this.edges = null;
    setNext_cursorIsSet(false);
    this.next_cursor = 0;
    setPrev_cursorIsSet(false);
    this.prev_cursor = 0;
  }

  public int getEdgesSize() {
    return (this.edges == null) ? 0 : this.edges.size();
  }

  public java.util.Iterator<Edge> getEdgesIterator() {
    return (this.edges == null) ? null : this.edges.iterator();
  }

  public void addToEdges(Edge elem) {
    if (this.edges == null) {
      this.edges = new ArrayList<Edge>();
    }
    this.edges.add(elem);
  }

  public List<Edge> getEdges() {
    return this.edges;
  }

  public EdgeResults setEdges(List<Edge> edges) {
    this.edges = edges;
    return this;
  }

  public void unsetEdges() {
    this.edges = null;
  }

  /** Returns true if field edges is set (has been assigned a value) and false otherwise */
  public boolean isSetEdges() {
    return this.edges != null;
  }

  public void setEdgesIsSet(boolean value) {
    if (!value) {
      this.edges = null;
    }
  }

  public long getNext_cursor() {
    return this.next_cursor;
  }

  public EdgeResults setNext_cursor(long next_cursor) {
    this.next_cursor = next_cursor;
    setNext_cursorIsSet(true);
    return this;
  }

  public void unsetNext_cursor() {
    __isset_bit_vector.clear(__NEXT_CURSOR_ISSET_ID);
  }

  /** Returns true if field next_cursor is set (has been assigned a value) and false otherwise */
  public boolean isSetNext_cursor() {
    return __isset_bit_vector.get(__NEXT_CURSOR_ISSET_ID);
  }

  public void setNext_cursorIsSet(boolean value) {
    __isset_bit_vector.set(__NEXT_CURSOR_ISSET_ID, value);
  }

  public long getPrev_cursor() {
    return this.prev_cursor;
  }

  public EdgeResults setPrev_cursor(long prev_cursor) {
    this.prev_cursor = prev_cursor;
    setPrev_cursorIsSet(true);
    return this;
  }

  public void unsetPrev_cursor() {
    __isset_bit_vector.clear(__PREV_CURSOR_ISSET_ID);
  }

  /** Returns true if field prev_cursor is set (has been assigned a value) and false otherwise */
  public boolean isSetPrev_cursor() {
    return __isset_bit_vector.get(__PREV_CURSOR_ISSET_ID);
  }

  public void setPrev_cursorIsSet(boolean value) {
    __isset_bit_vector.set(__PREV_CURSOR_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case EDGES:
      if (value == null) {
        unsetEdges();
      } else {
        setEdges((List<Edge>)value);
      }
      break;

    case NEXT_CURSOR:
      if (value == null) {
        unsetNext_cursor();
      } else {
        setNext_cursor((Long)value);
      }
      break;

    case PREV_CURSOR:
      if (value == null) {
        unsetPrev_cursor();
      } else {
        setPrev_cursor((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case EDGES:
      return getEdges();

    case NEXT_CURSOR:
      return Long.valueOf(getNext_cursor());

    case PREV_CURSOR:
      return Long.valueOf(getPrev_cursor());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case EDGES:
      return isSetEdges();
    case NEXT_CURSOR:
      return isSetNext_cursor();
    case PREV_CURSOR:
      return isSetPrev_cursor();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof EdgeResults)
      return this.equals((EdgeResults)that);
    return false;
  }

  public boolean equals(EdgeResults that) {
    if (that == null)
      return false;

    boolean this_present_edges = true && this.isSetEdges();
    boolean that_present_edges = true && that.isSetEdges();
    if (this_present_edges || that_present_edges) {
      if (!(this_present_edges && that_present_edges))
        return false;
      if (!this.edges.equals(that.edges))
        return false;
    }

    boolean this_present_next_cursor = true;
    boolean that_present_next_cursor = true;
    if (this_present_next_cursor || that_present_next_cursor) {
      if (!(this_present_next_cursor && that_present_next_cursor))
        return false;
      if (this.next_cursor != that.next_cursor)
        return false;
    }

    boolean this_present_prev_cursor = true;
    boolean that_present_prev_cursor = true;
    if (this_present_prev_cursor || that_present_prev_cursor) {
      if (!(this_present_prev_cursor && that_present_prev_cursor))
        return false;
      if (this.prev_cursor != that.prev_cursor)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(EdgeResults other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    EdgeResults typedOther = (EdgeResults)other;

    lastComparison = Boolean.valueOf(isSetEdges()).compareTo(typedOther.isSetEdges());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEdges()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.edges, typedOther.edges);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNext_cursor()).compareTo(typedOther.isSetNext_cursor());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNext_cursor()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.next_cursor, typedOther.next_cursor);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPrev_cursor()).compareTo(typedOther.isSetPrev_cursor());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrev_cursor()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.prev_cursor, typedOther.prev_cursor);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("EdgeResults(");
    boolean first = true;

    sb.append("edges:");
    if (this.edges == null) {
      sb.append("null");
    } else {
      sb.append(this.edges);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("next_cursor:");
    sb.append(this.next_cursor);
    first = false;
    if (!first) sb.append(", ");
    sb.append("prev_cursor:");
    sb.append(this.prev_cursor);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EdgeResultsStandardSchemeFactory implements SchemeFactory {
    public EdgeResultsStandardScheme getScheme() {
      return new EdgeResultsStandardScheme();
    }
  }

  private static class EdgeResultsStandardScheme extends StandardScheme<EdgeResults> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, EdgeResults struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EDGES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list24 = iprot.readListBegin();
                struct.edges = new ArrayList<Edge>(_list24.size);
                for (int _i25 = 0; _i25 < _list24.size; ++_i25)
                {
                  Edge _elem26; // required
                  _elem26 = new Edge();
                  _elem26.read(iprot);
                  struct.edges.add(_elem26);
                }
                iprot.readListEnd();
              }
              struct.setEdgesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NEXT_CURSOR
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.next_cursor = iprot.readI64();
              struct.setNext_cursorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PREV_CURSOR
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.prev_cursor = iprot.readI64();
              struct.setPrev_cursorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, EdgeResults struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.edges != null) {
        oprot.writeFieldBegin(EDGES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.edges.size()));
          for (Edge _iter27 : struct.edges)
          {
            _iter27.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(NEXT_CURSOR_FIELD_DESC);
      oprot.writeI64(struct.next_cursor);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PREV_CURSOR_FIELD_DESC);
      oprot.writeI64(struct.prev_cursor);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EdgeResultsTupleSchemeFactory implements SchemeFactory {
    public EdgeResultsTupleScheme getScheme() {
      return new EdgeResultsTupleScheme();
    }
  }

  private static class EdgeResultsTupleScheme extends TupleScheme<EdgeResults> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EdgeResults struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetEdges()) {
        optionals.set(0);
      }
      if (struct.isSetNext_cursor()) {
        optionals.set(1);
      }
      if (struct.isSetPrev_cursor()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetEdges()) {
        {
          oprot.writeI32(struct.edges.size());
          for (Edge _iter28 : struct.edges)
          {
            _iter28.write(oprot);
          }
        }
      }
      if (struct.isSetNext_cursor()) {
        oprot.writeI64(struct.next_cursor);
      }
      if (struct.isSetPrev_cursor()) {
        oprot.writeI64(struct.prev_cursor);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EdgeResults struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list29 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.edges = new ArrayList<Edge>(_list29.size);
          for (int _i30 = 0; _i30 < _list29.size; ++_i30)
          {
            Edge _elem31; // required
            _elem31 = new Edge();
            _elem31.read(iprot);
            struct.edges.add(_elem31);
          }
        }
        struct.setEdgesIsSet(true);
      }
      if (incoming.get(1)) {
        struct.next_cursor = iprot.readI64();
        struct.setNext_cursorIsSet(true);
      }
      if (incoming.get(2)) {
        struct.prev_cursor = iprot.readI64();
        struct.setPrev_cursorIsSet(true);
      }
    }
  }

}

