/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.twitter.flockdb.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ExecuteOperationType implements org.apache.thrift.TEnum {
  Add(1),
  Remove(2),
  Archive(3),
  Negate(4);

  private final int value;

  private ExecuteOperationType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ExecuteOperationType findByValue(int value) { 
    switch (value) {
      case 1:
        return Add;
      case 2:
        return Remove;
      case 3:
        return Archive;
      case 4:
        return Negate;
      default:
        return null;
    }
  }
}
