/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.twitter.flockdb.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Priority implements org.apache.thrift.TEnum {
  Low(1),
  Medium(2),
  High(3);

  private final int value;

  private Priority(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Priority findByValue(int value) { 
    switch (value) {
      case 1:
        return Low;
      case 2:
        return Medium;
      case 3:
        return High;
      default:
        return null;
    }
  }
}
